# Conclusion

The United States of America houses the most number of immigrants than any other country in the world. Not only are the international migration figures very high, but the domestic migration figures are also quite high in the United States. People migrate from one state to another, from one county to another county within the same state due to a variety of reasons. In this project, we set about analyzing the migration trends within the US over the past 5 years and found some interesting findings.


One of the many features that we analyzed in the migration patterns is income. We observed that the subset of the population who make **less than `$10,000 USD` per year migrates the most and the ones who earn upwards of `$200,000 USD` tend to migrate the least**. Another important feature that influences migration patterns is age. People who are young and less than 25 years of age migrate the most and the proportion of **the population that migrates keeps on decreasing with an increase in age**. One possible reason for this could be that people who are young tend to move around more in search of better education and employment opportunities.


Another crucial trend that we observed in the migration patterns over the past 5 years was a **sudden increase in domestic migration in the year 2017**. The migration figures peaked in 2017, came down over the next two years, and then increased again in 2020. In 2017, the United States government imposed several reforms that had a major impact on the immigration pattern. Some of these were the RAISE Act, Kate’s Law, a Border wall with Mexico, a pause on granting “Green Cards” and so on. Many of these new laws impacted people’s lives and forced them to migrate in search of safe, inexpensive neighborhoods and better employment opportunities.


We also observed the migration pattern with respect to the various states in the country. **Texas is one of the very few states where the inflow migration is greater than the outflow migration**. One of the many reasons could be low tax rates in Texas. Hence a majority of the migrants prefer to settle in Texas as compared to other states. Of all the states, the outflow migration is maximum in California. One of the many reasons for this trend could be the cost of living. It is far more expensive to live in California as compared to any other state in the United States and being a tech hub, remote work is very popular, giving people the flexibility to move around. In very few states like Arizona, Nevada, and Washington State, interstate migration dominates the intra-state migration. One possible reason could be the limited education and employment opportunities in these states which force people to move to other states. We also analyzed the average gross income of states over the span of 5 years to check if it played a major role in influencing the migration trend. No specific trend was found, the AGI increased in some states over in some age groups but decreased in the case of other age groups.


We would like to summarize this project and conclude by saying that migration patterns in the US can vary significantly over time and can be influenced by a variety of factors such as economic conditions, political developments, natural disasters, and other events. The United States has a long history of immigration and has historically been a destination for people from around the world seeking new opportunities and a better way of life. The U.S. has also experienced significant internal migration, with people moving between states and regions for a variety of reasons.
 
